on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - develop
    paths:
      - 'test_file.py'
  pull_request:
    branches:
      - develop

jobs:
  code-linting:
    runs-on: ubuntu-latest
    name: "Code linting"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/checkout@v2
      - name: "Install test package"
        run: pip install -U nox
      - name: "Run formatters"
        run: nox --non-interactive -e format
